slogan: 'Do not panic!'

show_heart: true

show_slogan: true

menu:
  - title: Archives
    url: archives
    intro: 'All the articles.'
  - title: Tags
    url: tags
    intro: 'All the tags.'
  - title: About
    url: about
    intro: 'About me.'

links:
  - title: X(Twitter)
    url: https://x.com/without_horn
    intro: "Yalda's X repository."
    icon: 'fa fa-twitter'
  - title: 'Github'
    url: http://www.github.com/guocaoyi
    intro: 'My Github account.'
    icon: 'fa fa-github'

widgets:
  - search
  - category
  - tagcloud
  - recent_posts
  - links

# 百度统计
baidu:
  enable: true
  siteid: b6ea6ca0c389aa294890b81f26dcc186

google_analytics:
  enable: true
  siteid: G-RGH70FJBTF
