# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

jobs:
  # Build job
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and build
        run: |
          npm ci
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          ssh-key: ${{ secrets.PAGES_PUB }}
          token: ${{ secrets.PAGES_PUB }}
          branch: main
          folder: public # The folder the action should deploy.
          clean: true
          clean-exclude: |
            public/CNAME
          silent: true
